-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."warehouses" add column "number_of_employees" integer
--  null default '0';
